### ISSUE TITLE
TypeError 'range'

### ISSUE THREAD

**Issue by lodewijkvanderpol** [kmcroft13/submit-googleforms-to-trello#1]
Hi! Thanks for this code, it seems great, however, I get an error on running this code:

Cannot read property 'range' from undefined

How can I solve this?

**Comment by ltang5msu** [comment]
I also get this issue and would love to learn about a fix!  I also would love examples of how the data is added (totally not a coder here!), particularly about labels and applying conditional logic.  Thanks!

**Comment by KeiranWDigital** [comment]
I had this issue, you need to create a script from the spreadsheet of form responses. 

Then set the trigger to be from spreadsheet and then "On form submit"

**Comment by kylepinecroft** [comment]
Sorry for the (very long) delays here, and thanks for the feedback. I've made some updates to the documentation to make the suggestions by @KeiranWDigital a bit more clear. Let me know if you still have issues!
