### ISSUE TITLE
No card is appearing under my board

### ISSUE THREAD

**Issue by D33Force** [kmcroft13/submit-googleforms-to-trello#2]
Hello! I followed the instructions to a T, ive sent several test forms and none of them are appearing in my board?

I do get this when 'running' the code
`TypeError: Cannot read property 'range' of undefined
onFormSubmit	@ Code.gs:3`

I'm not sure what I'm missing or doing wrong to get the cards to appear, i added the Key, token, list and label but still no cards

**Comment by kylepinecroft** [comment]
Hi @D33Force, apologies for the long delay here. Can you take a look at the suggestions in issue #1 and see if they work for you?
