### ISSUE TITLE
Invalid Object ID

### ISSUE THREAD

**Issue by henneusj** [kmcroft13/submit-googleforms-to-trello#4]
Hi, love your code so far. I've been having this issue.

everytime i submit a new response, i get this error : 
`Exception: Request failed for https://api.trello.com returned code 400. Truncated server response: {"message":"Invalid objectId","error":"ERROR"} (use muteHttpExceptions option to examine full response)
    at createTrelloCard(Untitled 2:79:16)
    at onFormSubmit(Untitled 2:3:4)`

if i add MuteHttpExceptions : True at the post payload (Line65) , script show as completed but no trello card is created.

Are you able to advise? 

thanks

**Comment by mxfl** [comment]
Hey, I know it's been a long time. But did you find a solution? I get the same error message. Thank you very much.

**Comment by kylepinecroft** [comment]
Hello, so sorry for the delay! There was a bug with how the payload data was passed. This has been resolved in the latest commit, so labels should work correctly now.
