### ISSUE TITLE
Tip jar for the developer

### ISSUE THREAD

**Issue by vineoak** [kmcroft13/submit-googleforms-to-trello#6]
Hi!

Nice code, would like to buy you a coffee or beer but did not find a way to do that. You saved me at least half a day.

**Comment by vineoak** [comment]
Well, in any case thank you for sharing the code :)

**Comment by kylepinecroft** [comment]
Hey! So sorry for the delay I clearly haven't been staying up to date on this. But thanks for the comment! No need for the beer money, the sentiment alone is appreciated.

You also inspired me to some time updating the code, fixing a few things, and updating the docs to reflect the latest buttons, etc. Hopefully others will continue to find this useful :)
